language: cpp

dist: Trusty

compiler:
  - gcc

os:
  - linux

before_install:

  - sudo apt-get update
  - sudo apt-get install cmake make libbz2-dev libdb++-dev libdb-dev libssl-dev openssl libreadline-dev autoconf libtool git ntp libcurl4-openssl-dev g++
  - BOOST_ROOT=$HOME/opt/boost_1_57_0
  - sudo apt-get update
  - sudo apt-get install autotools-dev build-essential libbz2-dev libicu-dev python-dev
  - wget -c 'http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download' -O boost_1_57_0.tar.bz2
  - [ $( sha256sum boost_1_57_0.tar.bz2 | cut -d ' ' -f 1 ) == "910c8c022a33ccec7f088bd65d4f14b466588dda94ba2124e78b8c57db264967" ] || ( echo 'Corrupt download' ; exit 1 )
  - tar xjf boost_1_57_0.tar.bz2
  - cd boost_1_57_0/
  - ./bootstrap.sh "--prefix=$BOOST_ROOT"
  - ./b2 install

install:

script: 
  - cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=Release . && make