language: cpp

dist: xenial
sudo: required
services:
  - docker

compiler:
  - gcc

git:
  submodules: true

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake make libbz2-dev libdb++-dev libdb-dev libssl-dev openssl libreadline-dev autoconf libtool git ntp libcurl4-openssl-dev g++
  - sudo apt-get install autotools-dev build-essential libbz2-dev libicu-dev python-dev
  - sudo apt-get install libboost-all-dev

install: true

script:
  - cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=Release . && make